Last Four functions of Read Block
abhijnanacharya/CS-525-Assign1-Storage_Mgr pull request #10
Opened 2024-02-05 20:19 UTC by htnushree

Added last 4 function of read block.

2024-02-06 00:41 UTC, abhijnanacharya requested changes

2024-02-06 00:41 UTC, abhijnanacharya commented on storage_mgr.c
> +    if(curBlockPos == getNumberOfBlocks(fHandle) - 1){
getNumberofBlocks() not defined;
getBlockPos() not defined

Please FIX THIS ASAP

2024-02-06 07:26 UTC, htnushree reviewed
please discard this commit.

2024-02-07 01:37 UTC, abhijnanacharya approved these changes

2024-02-07 01:37 UTC, merged